import type { Alert, Watch } from "./types";

const now = Date.now();

export const MOCK_WATCHES: Watch[] = [
  {
    id: "watch-chrome-update-orange",
    name: "Topps Chrome Update Orange",
    must_include: ["Topps", "Chrome", "Update", "Orange"],
    must_exclude: ["lot", "reprint", "digital"],
    year: null,
    max_price: 100,
    alert_below_pct: 30,
    buying: ["FIXED_PRICE"],
    enabled: true,
    last_median: null,
    last_comp_count: null,
    last_scanned_at: null,
    hit_count: 0,
    created_at: new Date(now - 1 * 86400000).toISOString(),
  },
  {
    id: "watch-mahomes",
    name: "Mahomes Prizm PSA 10",
    must_include: ["Mahomes", "Prizm", "PSA 10"],
    must_exclude: ["lot", "reprint", "digital", "optic"],
    year: 2023,
    max_price: 80,
    alert_below_pct: 30,
    buying: ["AUCTION", "FIXED_PRICE"],
    enabled: true,
    last_median: 71,
    last_comp_count: 14,
    last_scanned_at: new Date(now - 48 * 60 * 1000).toISOString(),
    hit_count: 1,
    created_at: new Date(now - 5 * 86400000).toISOString(),
  },
  {
    id: "watch-elly",
    name: "Elly De La Cruz Chrome 1st PSA 10",
    must_include: ["Elly", "De La Cruz", "Chrome", "PSA 10"],
    must_exclude: ["lot", "reprint", "bowman"],
    year: 2024,
    max_price: 60,
    alert_below_pct: 30,
    buying: ["AUCTION", "FIXED_PRICE"],
    enabled: true,
    last_median: 52,
    last_comp_count: 9,
    last_scanned_at: new Date(now - 48 * 60 * 1000).toISOString(),
    hit_count: 1,
    created_at: new Date(now - 3 * 86400000).toISOString(),
  },
  {
    id: "watch-nabers",
    name: "Nabers Optic Rated Rookie PSA 10",
    must_include: ["Nabers", "Optic", "PSA 10"],
    must_exclude: ["lot", "prizm"],
    year: 2024,
    max_price: 45,
    alert_below_pct: 30,
    buying: ["AUCTION", "FIXED_PRICE"],
    enabled: true,
    last_median: 38,
    last_comp_count: 6,
    last_scanned_at: new Date(now - 26 * 3600000).toISOString(),
    hit_count: 1,
    created_at: new Date(now - 2 * 86400000).toISOString(),
  },
  {
    id: "watch-wemby",
    name: "Wembanyama Prizm PSA 10",
    must_include: ["Wembanyama", "Prizm", "PSA 10"],
    must_exclude: ["lot", "reprint", "silver"],
    year: 2023,
    max_price: 120,
    alert_below_pct: 30,
    buying: ["AUCTION", "FIXED_PRICE"],
    enabled: true,
    last_median: 94,
    last_comp_count: 11,
    last_scanned_at: new Date(now - 90 * 60 * 1000).toISOString(),
    hit_count: 1,
    created_at: new Date(now - 4 * 86400000).toISOString(),
  },
  {
    id: "watch-ohtani",
    name: "Ohtani Topps Chrome PSA 10",
    must_include: ["Ohtani", "Chrome", "PSA 10"],
    must_exclude: ["lot", "reprint", "stadium"],
    year: 2023,
    max_price: 90,
    alert_below_pct: 30,
    buying: ["FIXED_PRICE"],
    enabled: true,
    last_median: 78,
    last_comp_count: 8,
    last_scanned_at: new Date(now - 3 * 3600000).toISOString(),
    hit_count: 1,
    created_at: new Date(now - 6 * 86400000).toISOString(),
  },
  {
    id: "watch-lamar",
    name: "Lamar Downtown PSA 10",
    must_include: ["Lamar", "Downtown", "PSA 10"],
    must_exclude: ["lot", "reprint"],
    year: 2024,
    max_price: 200,
    alert_below_pct: 30,
    buying: ["AUCTION", "FIXED_PRICE"],
    enabled: true,
    last_median: 165,
    last_comp_count: 5,
    last_scanned_at: new Date(now - 70 * 60 * 1000).toISOString(),
    hit_count: 1,
    created_at: new Date(now - 1 * 86400000).toISOString(),
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: "alert-1",
    watch_id: "watch-mahomes",
    watch_name: "Mahomes Prizm PSA 10",
    item_id: "v1|334567890123|0",
    title: "2023 Panini Prizm Patrick Mahomes II #15 PSA 10 Gem Mint",
    image_url: null,
    live_price: 42,
    shipping: 4.99,
    live_total: 46.99,
    median: 71,
    comp_count: 14,
    pct_of_median: 66.2,
    buying: "FIXED_PRICE",
    ends_at: null,
    ebay_url: "https://www.ebay.com/itm/334567890123",
    point130_url: "sample",
    seller_feedback: 1840,
    seen: false,
    comp_status: "ok",
    created_at: new Date(now - 2 * 3600000).toISOString(),
  },
  {
    id: "alert-2",
    watch_id: "watch-elly",
    watch_name: "Elly De La Cruz Chrome 1st PSA 10",
    item_id: "v1|256987654321|0",
    title: "2024 Topps Chrome Elly De La Cruz RC PSA 10",
    image_url: null,
    live_price: 28,
    shipping: 0,
    live_total: 28,
    median: 52,
    comp_count: 9,
    pct_of_median: 53.8,
    buying: "AUCTION",
    ends_at: new Date(now + 5 * 3600000).toISOString(),
    ebay_url: "https://www.ebay.com/itm/256987654321",
    point130_url: "sample",
    seller_feedback: 412,
    seen: false,
    comp_status: "ok",
    created_at: new Date(now - 6 * 3600000).toISOString(),
  },
  {
    id: "alert-3",
    watch_id: "watch-nabers",
    watch_name: "Nabers Optic Rated Rookie PSA 10",
    item_id: "v1|123111222334|0",
    title: "2024 Panini Donruss Optic Malik Nabers Rated Rookie PSA 10",
    image_url: null,
    live_price: 24,
    shipping: 4.5,
    live_total: 28.5,
    median: 38,
    comp_count: 6,
    pct_of_median: 75.0,
    buying: "FIXED_PRICE",
    ends_at: null,
    ebay_url: "https://www.ebay.com/itm/123111222333",
    point130_url: "sample",
    seller_feedback: 92,
    seen: false,
    comp_status: "ok",
    created_at: new Date(now - 20 * 3600000).toISOString(),
  },
  {
    id: "alert-4",
    watch_id: "watch-wemby",
    watch_name: "Wembanyama Prizm PSA 10",
    item_id: "v1|445566778899|0",
    title: "2023 Panini Prizm Victor Wembanyama Rookie PSA 10",
    image_url: null,
    live_price: 69,
    shipping: 5.99,
    live_total: 74.99,
    median: 94,
    comp_count: 11,
    pct_of_median: 79.8,
    buying: "AUCTION",
    ends_at: new Date(now + 11 * 3600000).toISOString(),
    ebay_url: "https://www.ebay.com/itm/445566778899",
    point130_url: "sample",
    seller_feedback: 2204,
    seen: false,
    comp_status: "ok",
    created_at: new Date(now - 90 * 60 * 1000).toISOString(),
  },
  {
    id: "alert-5",
    watch_id: "watch-ohtani",
    watch_name: "Ohtani Topps Chrome PSA 10",
    item_id: "v1|998877665544|0",
    title: "2023 Topps Chrome Shohei Ohtani PSA 10 Dodgers",
    image_url: null,
    live_price: 61,
    shipping: 0,
    live_total: 61,
    median: 78,
    comp_count: 8,
    pct_of_median: 78.2,
    buying: "FIXED_PRICE",
    ends_at: null,
    ebay_url: "https://www.ebay.com/itm/998877665544",
    point130_url: "sample",
    seller_feedback: 640,
    seen: true,
    comp_status: "ok",
    created_at: new Date(now - 14 * 3600000).toISOString(),
  },
  {
    id: "alert-6",
    watch_id: "watch-lamar",
    watch_name: "Lamar Downtown PSA 10",
    item_id: "v1|112233445566|0",
    title: "2024 Panini Downtown Lamar Jackson PSA 10",
    image_url: null,
    live_price: 118,
    shipping: 12,
    live_total: 130,
    median: 165,
    comp_count: 5,
    pct_of_median: 78.8,
    buying: "AUCTION",
    ends_at: new Date(now + 3 * 3600000).toISOString(),
    ebay_url: "https://www.ebay.com/itm/112233445566",
    point130_url: "sample",
    seller_feedback: 77,
    seen: false,
    comp_status: "unavailable",
    created_at: new Date(now - 40 * 60 * 1000).toISOString(),
  },
];
